fix?
FHIR/fhir-test-cases pull request #203
Opened 2024-11-26 09:41 UTC by grahamegrieve

2024-11-26 10:07 UTC, pieter-edelman-nictiz requested changes

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> +      "short" : "Requester",
`.comment` now reverts to the base definition from FHIR. This is not the desired behavior, it should be the value from the data type profile used here.

On the other hand, `.short`, `.definition` and `.alias` now use the correct values (they come from the base profile and are not overridden by anything).

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> +        "identity" : "zib-nursingintervention-v3.2-2020EN",
Adding this mapping is the desired behavior.

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> +      "short" : "Extension",
The extension is not included in the test case. Should this be added as well?

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> -      "condition" : ["ele-1"],
Not sure why this `condition` is removed. Shouldn't it always be present?

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> -      "fixedUri" : "http://nictiz.nl/fhir/StructureDefinition/ext-CarePlan-MaterialUsed",
Not sure if this is due to the fact that the extension is not included in the test case, but I think it should not be removed?

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> +      "comment" : "A performer MAY also be a participant in the care plan.",
Like above:

.comment now reverts to the base definition from FHIR. This is not the desired behavior, it should be the value from the data type profile used here.

On the other hand, .short, .definition and .alias now use the correct values (they come from the base profile and are not overridden by anything).

2024-11-26 10:07 UTC, pieter-edelman-nictiz commented on rX/snapshot-generation/nl-core-NursingIntervention-output.json
> +        "identity" : "zib-nursingintervention-v3.2-2020EN",
Inheriting this mapping key is the desired behavior.

2024-11-28 05:41 UTC, grahamegrieve commented
Closing this - the test itself was set up wrong. See next PR

2024-11-28 05:41 UTC, closed without merging